### ISSUE TITLE
Fix the output of the /roll command.

### ISSUE THREAD

**Issue by dmccoystephenson** [DansPlugins/Medieval-Roleplay-Engine#144]
![image.png](https://images.zenhubusercontent.com/5e320b6f2bd28c8043a7b709/183fbe6d-7f81-40ae-bf3f-5b932a7f2e4f)

**Comment by dmccoystephenson** [comment]
I think we just need to toString() the results on this line:

https://github.com/DansPlugins/Medieval-Roleplay-Engine/blob/4dc63720d9a008f4a2fe87092404507115695965/src/main/java/rpsystem/Commands/RollCommand.java#L54

**Comment by UndeadZeratul** [comment]
Hmm, yeah I think the `getRoleResults()` could use the `toString()`, but it looks like `getTotalRole()` already works as-is?

**Comment by UndeadZeratul** [comment]
Ah, ok there's a bit more to this it seems.  So `RollHistory` contains a collection of `RollResult`s and a grand total value.  The `RollResult`s each contain a collection of individual dice roll values and that result's total value.

My interpretation of the History's intention is that you could roll multiple sets of dice, each containing their own individual die roll results and the roll's total.  Each of those results' must then get summed together for the history's grand total.

We might want to work out a nicer response message, but for now I'm hoping just looping through each result and showing it's individual rolls and the total should suffice.
